### ISSUE TITLE
`bit_range` must be initialized when renaming bitfields

### ISSUE THREAD

**Issue by MabezDev** [stm32-rs/svdtools#113]
I want to rename some register blocks, and their respective bitfields on a given peripheral. Here is my yaml:

```yaml
SYSTIMER:
  _modify:
      VALUE_LO:
        name: UNIT0_VALUE_LO
      VALUE_HI:
        name: UNIT0_VALUE_HI
      UPDATE:
        name: UNIT0_OP
        fields:
          TIMER_VALUE_VALID:
            name: TIMER_UNIT0_VALUE_VALID 
          TIMER_UPDATE:
            name: TIMER_UNIT0_UPDATE
```

The registers are correctly renamed, but when I try and rename the bit fields I get the following error:

```
Error: Processing device `ESP32-S2`

Caused by:
    0: According to `SYSTIMER`
    1: Processing peripheral `SYSTIMER`
    2: Modifying registers matched to `UPDATE`
    3: `Build error: `bit_range` must be initialized
```

Have I got the syntax wrong, or is this a bug?

**Comment by MabezDev** [comment]
Even if I add the bit range fields manually, it still complains.

```yaml
SYSTIMER:
  _modify:
      VALUE_LO:
        name: UNIT0_VALUE_LO
      VALUE_HI:
        name: UNIT0_VALUE_HI
      UPDATE:
        name: UNIT0_OP
        fields:
          TIMER_VALUE_VALID:
            name: TIMER_UNIT0_VALUE_VALID
            bitOffset: 30
            bifWidth: 1
          TIMER_UPDATE:
            name: TIMER_UNIT0_UPDATE
            bitOffset: 31
            bifWidth: 1
```

**Comment by MabezDev** [comment]
Got a working solution, need to modify the register name first, then use the renamed register to rename the bitfields.

```yaml



SYSTIMER:
  _modify:
    VALUE_LO:
      name: UNIT0_VALUE_LO
    VALUE_HI:
      name: UNIT0_VALUE_HI
    UPDATE:
      name: UNIT0_OP
  UNIT0_OP:
    _modify:
      TIMER_VALUE_VALID:
        name: TIMER_UNIT0_VALUE_VALID
      TIMER_UPDATE:
        name: TIMER_UNIT0_UPDATE  
```
