### ISSUE TITLE
svdtools does not handle derivin registers from another peripheral

### ISSUE THREAD

**Issue by ithinuel** [stm32-rs/svdtools#146]
Example:

```yaml
PADS_QSPI:
  _delete:
    "VOLTAGE_SELECT":
  _derive:
    "VOLTAGE_SELECT":
      _from: "PADS_BANK0.VOLTAGE_SELECT"
```

fails with `svdtools.patch.SvdPatchError: register PADS_BANK0.VOLTAGE_SELECT not found`

Could be related to [`def derive_from`](https://github.com/stm32-rs/svdtools/blob/master/svdtools/patch.py#L888-L902) searching for the target register in the parent only rather than decomposing the target register's name.
