### ISSUE TITLE
_delete interrupts is incompatible with _derive peripheral

### ISSUE THREAD

**Issue by burrbull** [stm32-rs/svdtools#56]
I've tried to add
```
_derive:
  TIM5: TIM2
```
in `stm32l552.yaml`, but after this
```
TIM2:
  _delete:
    _interrupts:
      - TIM2_*
```
doesn't work.
