### ISSUE TITLE
Field matching for _replace_enum

### ISSUE THREAD

**Issue by allexoll** [stm32-rs/svdtools#97]
Field with `*` matching only patches the first occurrence of the match:

```yaml
SYSCON:
  STARTERP1:
    "SPI*":
      _replace_enum:
        DISABLED: [0, Disabled]
        ENABLED: [1, Enabled]
```

this only matches SPI0, and not SPI1. I'm not sure if this is an intended behavior or if this is a bug?

applicable svd: https://gist.github.com/allexoll/2dc8d7ca2eca44bfe2b17f0c0769eba7
